---
jobs:
- broker_redis
- indexer
- elasticsearch
- web_logstash
- kibana
properties:
  redis:
    host: 127.0.0.1
    port: 6380
    # password: redis
    broker_key: logstash
  elasticsearch:
    host: 127.0.0.1
    hosts:
    - 127.0.0.1
  indexer:
    output:
      stdout: true
  kibana:
    port: 5601
